S03US04 modal components with inputs and buttons
WildCodeSchool/2023-03-JS-TLSE-P3-AFAC974 pull request #2
Opened 2023-06-19 09:33 UTC by HugoCarnazza

2023-06-19 13:15 UTC, JulienC90 approved these changes

2023-06-19 13:50 UTC, aimach requested changes

2023-06-19 13:50 UTC, aimach commented on frontend/src/components/Input.jsx
> +    if (type === "file") {
utiliser un switch

2023-06-19 13:50 UTC, aimach commented on frontend/src/components/GreyButton.jsx
> +      className="bg-red-800"
plutôt bg-grey non ?

2023-06-19 13:50 UTC, aimach commented on frontend/src/components/AddArtwork.jsx
> +              <GreyButton text="Annuler" handleCancel={handleCancel} />
si vous pensez appeler ailleurs dans votre application ce duo de bouton, il pourrait être intéressant de le mettre dans un composant à part.

2023-06-20 15:13 UTC, JulienC90 approved these changes

2023-06-20 15:14 UTC, JulienC90 commented on frontend/src/components/GreyButton.jsx
> +      className="bg-red-800"
Il s'agissait d'un test Tailwind. Non concluant pour le coup.

2023-06-20 15:25 UTC, merged